require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - spec/fixtures/**/*
    - tmp/**/*

Rails:
  Enabled: true

# Style -----------------------------------------------------------------------

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

# Layout ----------------------------------------------------------------------

Layout/LineLength:
  Max: 100

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    associations:
      - has_one
      - has_many
      - belongs_to
      - has_and_belongs_to_many
  ExpectedOrder:
      - module_inclusion
      - constants
      - associations
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods

# RSpec -----------------------------------------------------------------------

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 22

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/VariableName:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/StubbedMock:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
