version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hospital
      POSTGRES_PASSWORD: password
  web:
    platform: linux/x86_64
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/hospital
    ports:
      - "3000:3000"
    depends_on:
      - db
