default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: hospital
  password: password
  pool: 5

development:
  <<: *default
  database: hospital_development


test:
  <<: *default
  database: hospital_test
