default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'db' %>
  username: <%= ENV['DB_USERNAME'] || 'hospital' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>
  pool: 5

development:
  <<: *default
  database: hospital_development


test:
  <<: *default
  database: hospital_test
